sudo: false
language: ruby
rvm:
- 2.1.0
branches:
  only:
  - master
env:
  global:
    - GH_PAGES_REPO=axsemantics/api-docs
    - GH_PAGES_DOMAIN=apidocs.ax-semantics.com
    - GH_PAGES_BASEDIR=build
cache: bundler
script: ". ./travis-deploy.sh"
